name: Update

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Update
        env:
          NODE_ENV: production
          PARSER_API_KEY: ${{ secrets.PARSER_API_KEY }}
          PARSER_MODEL: ${{ secrets.PARSER_MODEL }}
          PARSER_BASE_URL: ${{ secrets.PARSER_BASE_URL }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          FIXER_BASE_URL: ${{ secrets.FIXER_BASE_URL }}
          FIXER_MODEL: ${{ secrets.FIXER_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          ALIYUN_API_KEY: ${{ secrets.ALIYUN_API_KEY }}	
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_API_KEY }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}
        run: |
          set +e
          mkdir -p ~/.ssh ./data
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
          git clone --depth 1 git@github.com:vvtommy/llmpricing.app.git tmp/
          cd tmp/packages/types
          pnpm install --frozen-lockfile
          pnpm tsc
          cd ../crawler
          pnpm install --frozen-lockfile
          npx playwright install chrome --with-deps
          pnpm tsc
          pnpm run start
          mv ./src/data ../../../

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'data/*.json'
